### ISSUE TITLE
Problem: Teleportation / Water Particule

### ISSUE THREAD

**Issue by benda95280** [ninjaknights/CosmeticMenu#1]
Hello,

Nice plugin, very funny, my child like it !

But i've saw some problems:
- Do not work when back to Default World with TP (Add event: onLevelChange ?)
- No particule with "Water"

**Comment by Jean-TKG** [comment]
The plugin is still in alpha build so it needs lots of works and many other features will be added to make the plugin easier for the users who are using it.

**Comment by benda95280** [comment]
Sorry, i was already tring it 👍

**Comment by Jean-TKG** [comment]
No problem and thanks for telling me about Defaut World, I will now work on this to make it work.

**Comment by benda95280** [comment]
I'll think you need to be sur when you'r inside the onInteract() you are in good world. (Lobby / Default World )
Maybe config file to choose the world ?

Rgds.
(I was doing it before posting an issue here :) )
