### ISSUE TITLE
Items Fix?

### ISSUE THREAD

**Issue by arkhamservers** [ninjaknights/CosmeticMenu#2]
Could you make it so when u click the cosmetics item it saves your inventory before you use it and then after you close the cosmetics it returns your inventory before you used the item? please reply its inportant

**Comment by Jean-TKG** [comment]
I will try to fix this as fast as I can

**Comment by Jean-TKG** [comment]
Sorry but I couldn't fix what you wanted cus I am busy making a website if I get time I will try my best to do it.
