### ISSUE TITLE
Need Ideas

### ISSUE THREAD

**Issue by Jean-TKG** [ninjaknights/CosmeticMenu#3]
write some ideas for me to add.

**Comment by jaylac2000** [comment]
add configurable options

**Comment by Jean-TKG** [comment]
In the future I will but what should I add in that configurable option

**Comment by benda95280** [comment]
- Worlds where it apply (And removed if TP)
- If applied to OP or not
- New item: Snowball (When player hitted, random thing like, inverse forwand and go back, or slow for 5s) With reloading time for 10s

**Comment by jaylac2000** [comment]
add sword that enables PVP only to players with it out

**Comment by Jean-TKG** [comment]
> * Worlds where it apply (And removed if TP)
> * If applied to OP or not
> * New item: Snowball (When player hitted, random thing like, inverse forwand and go back, or slow for 5s) With reloading time for 10s

in v2.0 is a full rewrite of the plugin and will have a config for these kind of things and I will think about the snowball idea

**Comment by Jean-TKG** [comment]
> add sword that enables PVP only to players with it out

this does not sound like something that needs to be added as a cosmetic.

**Comment by Jean-TKG** [comment]
There now a discord https://discord.gg/PsMYb6Q you can give me ideas here

**Comment by benda95280** [comment]
> > add sword that enables PVP only to players with it out
> 
> this does not sound like something that needs to be added as a cosmetic.

Doesn't seems a bad idea

**Comment by jaylac2000** [comment]
^ it is more for popular servers where people need to wait in the lobby in order to join they will at least have something to do

**Comment by jaylac2000** [comment]
^ this feature is more common on a java server

**Comment by Jean-TKG** [comment]
Hmm never heard it before I'll research it

**Comment by Jean-TKG** [comment]
What should I add to the config (cus I'm working on it now)

**Comment by Johnsonk79** [comment]
Add the option to maybe enable the cosmetics with a single command instead of pairing to a certain world? This is because I am currently using the plugin Hotbar, so if I also enable this plugin the two plugins will have conflict against each other. Thanks!

**Comment by Jean-TKG** [comment]
yeah that's a good Idea I was planning on doing something like that for it can't get in other plugins way

**Comment by BroCrows** [comment]
Maybe add a permission where it gives all perms?

**Comment by Jean-TKG** [comment]
ok

**Comment by IceCruelStuff** [comment]
Maybe add pets that follow the owner?

**Comment by TheKnightGamer** [comment]
That's was part of the main plan of the plugin maybe if I get time I will start working on that.

**Comment by Jean-TKG** [comment]
> Maybe add pets that follow the owner?

That's was part of the main plan of the plugin maybe if I get time I will start working on that.

**Comment by jaylac2000** [comment]
Add more config options

- player death (true/false)
- player damage (true/false)
- allow item drop (true/false)
- consume items (true/false)

- add another item which can enable / disable player visibility 
- again with my old suggestion: add a sword which only enables pvp when in hand (even while in gamemode adventure) (true/false) to have it enabled. add a item name/lore (configurable) also the item configurable

**Comment by Jean-TKG** [comment]
Tomorrow I will start adding these features. If anyone has anymore questions go to the discord server https://discord.gg/PsMYb6Q

**Comment by jaylac2000** [comment]
add customization cooldown for tnt launcher - sry for all the suggestions this is the first, best lobby plugin ive found in pmmp yet and i am getting ideas from my java lobby system

**Comment by Jean-TKG** [comment]
3.13 add something I want to test for cooldown so I hope you guys like it and thanks for the suggestion it gives me new things to add.

**Comment by Jean-TKG** [comment]
Join the NinjaKnights Discord to give me your suggestions to add.
