### ISSUE TITLE
API Update

### ISSUE THREAD

**Issue by Bonunu** [ninjaknights/CosmeticMenu#9]
Hello!
Whenever I try to run CosmeticMenu on my Pocketmine Server, I get this error:

`Could not load plugin 'CosmeticMenu': Incompatible API version (plugin requires one of: 3.13.0)`

I'm confused about this because in the `plugin.yml` it says that the API is `3.13.0`.

**Comment by Jean-TKG** [comment]
Update your Pocketmine-MP.phar

**Comment by Bonunu** [comment]
OK, thanks!
